theme: jekyll-theme-time-machine
title: Mikado Testbuilders Kata

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include: 
  - docs
  - LICENSE.txt
  - docs/1_-_Introduction.md
  - docs/1 - Introduction.md

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false