theme: jekyll-theme-time-machine
title: Mikado Testbuilders Kata

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include: 
  - docs
  - LICENSE.txt
  - docs/1_-_Introduction.md
  - docs/2_-_Easy_Fix_Difficult_Test.md
  - docs/3_-_Building_Test_Data.md
  - docs/4_-_Mikado_Method_to_the_Rescue.md
  - docs/5_-_Conclusion.md
  - docs/Animation_Guide.md
  - docs/references/References.md
  - docs/references/Test_Data_Builders.md
  - docs/references/The_Mikado_Method.md

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false